### ISSUE TITLE
Please consider adding tests to the pypi package

### ISSUE THREAD

**Issue by vikraman** [jkbrzt/httpie#182]
This will allow running the tests when installing on gentoo linux for example.

**Comment by kmosiejczuk** [comment]
Sorry to comment on this necro-issue. I figured I'd do that rather than open a new issue on the same issue.

There are lots of python packages that include tests in the OpenBSD ports tree. Python dateutil and pytest are two packages off the top of my head that I know ship the tests in the PyPI tarball. I can come up with more examples if you'd like.

I can submit a pull request for the change to MANIFEST.in to include the tests in future if that is desirable.

**Comment by jakubroztocil** [comment]
Starting with v2.0.0 tests will be included in the pypi package.

**Comment by kmosiejczuk** [comment]
Thank you!
