### ISSUE TITLE
Access https urls when invoke as `https`

### ISSUE THREAD

**Issue by rainux** [jkbrzt/httpie#289]
Currently we can use this shortcut for access http url:

    http en.wikipedia.org

It would be nice if httpie support invoke as `https` (symlink `http` binary to `https` when installing), and access https url:

    https github.com

Thanks.

**Comment by derelk** [comment]
+1 for this feature.

**Comment by gvsmirnov** [comment]
:+1:

**Comment by adius** [comment]
:+1:

**Comment by jimbru** [comment]
+1 would be nice

**Comment by grepnull** [comment]
+1

**Comment by jpbernius** [comment]
+1

**Comment by danthegoodman** [comment]
+1

What about a flag that set the default scheme as 'https' when it was missing from the url? Then you could use an alias instead of having to create a symlink.

```
alias https='http --https'
```

**Comment by jdhoek** [comment]
:+1: 

## Rationale

HTTPS is slowly becoming the default on the open internet, and for development using HTTPS by default is increasingly a common scenario. I suspect that for a lot of users most calls now start like this:

```
http https://url
```

Instead of:

```
http url
```

(Optionally) replacing `http https://` with `https` makes sense to me from a user interface standpoint and seems to fit in well with the overall design of HTTPie. I actually tried that with a HTTPS URL because it seemed logical before finding out `https` wasn't available and explicitly declaring `https://` is needed.

@jkbrzt I am curious why this feature was removed from earlier versions; are there any downsides to this proposed feature?

**Comment by jkbrzt** [comment]
You can now use `--default-scheme`:

```bash
alias https='http --default-scheme=https'
```
