### ISSUE TITLE
support for HttpOnly & secure attributes

### ISSUE THREAD

**Issue by ebridges** [jkbrzt/httpie#403]
How can I configure httpie to support the `HttpOnly` and `secure` cookie attributes?

With default setup, if I hand-edit `HttpOnly` into the JSON file generated for a session I get this:

```
http: error: TypeError: create_cookie() got unexpected keyword arguments: [u'HttpOnly']
```

Similarly, if I hand-edit in an attribute of `"secure" : true` for a cookie, it causes httpie to not send the cookie.  If I add `"secure" : false`, it successfully sends the cookie.

**Comment by jkbrzt** [comment]
@ebridges I believe it should be `httponly`

**Comment by ebridges** [comment]
Odd.  I'm seeing cookies being set by Jetty that return `HttpOnly`:

![image](https://cloud.githubusercontent.com/assets/1581123/13463567/d8ae9430-e05a-11e5-89ea-87079306e111.png)

**Comment by jkbrzt** [comment]
Yes, but the internal attribute name used by the underlying Python libraries is lowercase `httpopnly` so it needs to be specified as such.

https://docs.python.org/2/library/cookie.html#morsel-objects

**Comment by ebridges** [comment]
But that link you reference says:

> The keys are case-insensitive.

**Comment by ebridges** [comment]
@jkbrzt can you reopen this, or otherwise respond to my point above?  Thanks

**Comment by sigmavirus24** [comment]
@ebridges a few things:

1. @jkbrzt was correct in closing this
1. @jkbrzt closed this for the wrong reason
1. This probably needs better documentation
1. A better way to debug this would be to serialize a session that had an HttpOnly cookie set on it
1. Try editing the JSON by hand with `"rest": {"HttpOnly": true}` because it looks like this is how the underlying library expects this to be passed.

**Comment by ebridges** [comment]
@sigmavirus24 

1. Fair enough, I guess.
2. What was the correct reason for closing it?
3. Fair enough.
4. I believe that's what I provided in my original post...and in the snippet from a Jetty session.
5. I'd prefer to have the app provide correct behavior rather than hand editing the request.  

Just to be clear: the server I'm interacting with responds with `HttpOnly`.  @jkbrzt claims the server should be sending `httponly`.  The underlying library claims to be agnostic (i.e. case insensitive).  Httpie claims that it is case sensitive.  I feel stuck in the middle.

I'm about ready to just move on and switch to a more reliable tool; but for the sake of completeness I hope that this can be resolved, since I really like this tool.

**Comment by jkbrzt** [comment]
@ebridges The `HttpOnly` flag on cookies is not relevant to a command line HTTP client like HTTPie — it is intended for web browsers. Since it's ignored and only sent from the server to the client, there's no practical reason to store it in the session files.

> According to the Microsoft Developer Network, HttpOnly is an additional flag included in a Set-Cookie HTTP response header. Using the HttpOnly flag when generating a cookie helps mitigate the risk of client side script accessing the protected cookie (if the browser supports it). 
> — https://www.owasp.org/index.php/HttpOnly

The `secure` flag has always been [supported](https://github.com/jkbrzt/httpie/blob/33eb9acd92b876ff86bfa39666b7610d1f93eb4c/httpie/sessions.py#L137) — it gets stored in the session files when the server specifies it, and such cookies are then correctly excluded from non-secure requests.

--
Btw, I wasn't claiming that the server should be sending lowercase `httponly`. I was just referring to the internal Python variable names which I noticed upon a very brief inspection of the source code. From that I incorrectly concluded that it should be specified in the session file as such. @sigmavirus24's suggestion would have probably been the correct way. But there's really no practical reason (known to me) for storing that flag because it does not get sent back to the server.
