### ISSUE TITLE
Broken input detection logic

### ISSUE THREAD

**Issue by ei-grad** [jkbrzt/httpie#457]
If you run
```
http -v httpbin.org/get > out.txt
```
from cron script, it will send POST query. This is absolutely wrong and unexpected behaviour. The ```--ignore-stdin``` option existence is ambiguous.

```
> cat out.txt
POST /get HTTP/1.1
Host: httpbin.org
Accept-Encoding: gzip, deflate
Accept: */*
Content-Length: 0
Connection: keep-alive
User-Agent: HTTPie/0.9.3



HTTP/1.1 405 METHOD NOT ALLOWED
Server: nginx
Date: Sat, 02 Apr 2016 00:23:40 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Allow: HEAD, OPTIONS, GET
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

**Comment by ei-grad** [comment]
An example of correct logic could be the following:
- if there is any data on stdin - then it is input
- if there is no data - stdin is not an input.

**Comment by jkbrzt** [comment]
@ei-grad Yes, this logic would allow for a much user-friendlier solution than the current one. I had considered it before adding the `--ignore-stdin` option but decided against it because of the following reasons:

The main problem is that for `stdin` it's hard/impossible to detect when there's no data because the input file remains open and `read()` on it blocks until it gets closed (which can be forever when run from cron). 

Consider this scenario:

```bash
$ cat | http httpie.org/post
```

HTTPie has no way of knowing that there's no data until you close the input with `^D`

The data can come at a later time:

```bash
$ { sleep 5; echo 'data!'; }  | http httpbin.org/post
```

Or a simplified version of what happens under the hood:

```bash
$ cat | python -c 'import sys; print(repr(sys.stdin.read()))'
```

Another (less severe) issue with this approach would be that even empty redirected stdin should be considered as "having data":

```bash
$ bin/possibly-get-some-output | http httpbin.org/post
```

**Comment by jkbrzt** [comment]
I'd love to get rid of `--ignore-stdin`, but I don't see a way around it. Please do correct me if any of my assumptions above are incorrect.

**Comment by ei-grad** [comment]
In all these scenarios it is still a valid behaviour to do ```sys.stdin.read()``` (which blocks until the EOF), and then see if there is any bytes of data, or not. Actually, ```httpie``` does ```sys.stdin.read()``` anyway currently:

- https://github.com/jkbrzt/httpie/blob/master/httpie/input.py#L152:
```
    def parse_args(self, env, args=None, namespace=None):
            <...>
            self._body_from_file(self.env.stdin)
            <...>
```

- https://github.com/jkbrzt/httpie/blob/master/httpie/input.py#L278:
```
    def _body_from_file(self, fd):
        <...>
        self.args.data = getattr(fd, 'buffer', fd).read()
```

**Comment by ei-grad** [comment]
Btw, this is one another bad thing - doing ```fd.read()``` without specified chunk size wouldn't allow to stream large request body effectively...

**Comment by jkbrzt** [comment]
> In all these scenarios it is still a valid behaviour to do sys.stdin.read() , 

Yes

> (which blocks until the EOF)

Yup 

> and then see if there are any bytes of data, or not. 

**If we do get EOF —**  it doesn't makes sense distinguishing between "has data" and "has no data" anymore. See the `bin/possibly-get-some-output` example above. 

**If we do NOT get EOF —** there's no way of knowing if there's data or not. That includes invocations from cron.  That's why  the `--ignore-stdin` option is needed to never start reading `stdin` in the first place.

> Actually, httpie currently does `sys.stdin.read()` anyway

Yes, I should know that

> Btw, this is one another bad thing - doing `fd.read()` without specified chunk size wouldn't allow to stream large request body effectively...

This is another issue. HTTPie doesn't support streamed uploads at the moment. It buffers the `stdin` data before making a request (as documented in the README). But even once the streamed uploads feature is implemented, it doesn't make any difference when it comes to the input data detection problem.

**Comment by AleksanderGrzybowski** [comment]
Oops, just hit this today, after a while of tcpdumping and 'Method Not Allowed' errors. Is this behavior documented somewhere?
