### ISSUE TITLE
Setting host header causes a python casting error

### ISSUE THREAD

**Issue by gonzalocasas** [jkbrzt/httpie#521]
I get a `TypeError` when trying to request a URL and passing a `Host` header to it. I tried with quotes and without, but nothing works.

See the following example where prefixing `m.` to the hostname causes an error:

```
$ http -v http://m.youtube.com Host:m.youtube.com

http: error: TypeError: Cannot mix str and non-str arguments
```

Compared to:

```
$ http -v http://m.youtube.com Host:youtube.com
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: youtube.com
User-Agent: HTTPie/0.9.6



HTTP/1.1 301 Moved Permanently
Content-Length: 0
Content-Type: text/html
Date: Thu, 22 Sep 2016 12:53:56 GMT
Location: http://www.youtube.com/
Server: YouTubeFrontEnd
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
```

The same request with curl works properly so definitely looks like something's off on httpie.

**Comment by bbamsch** [comment]
This may not be a bug in httpie, rather a bug in the underlying requests framework.

There appears to be an incorrect assumption made in requests.cookies.MockRequest, [see here](https://github.com/kennethreitz/requests/blob/master/requests/cookies.py#L52):
```
class MockRequest(object):
    ...
    def get_full_url(self):
        # Only return the response's URL if the user hadn't set the Host
        # header
        if not self._r.headers.get('Host'):
            return self._r.url
        # If they did set it, retrieve it and reconstruct the expected domain
        host = self._r.headers['Host']
        parsed = urlparse(self._r.url)
        # Reconstruct the URL as we expect it
        return urlunparse([
            parsed.scheme, host, parsed.path, parsed.params, parsed.query,
            parsed.fragment
        ])
    ...
```

In Python2 this works fine where str and unicode objects are allowed interchangably in urlunparse.

In Python3 this is an issue because ```host = self._r.headers['Host']``` may return a bytestring and ```        parsed = urlparse(self._r.url)```  returns a ParseResult with str objects. Combining these two causes urlunparse to throw a fit.

**Comment by bbamsch** [comment]
This issue has been resolved in the requests library.
https://github.com/kennethreitz/requests/issues/3597

**Comment by gonzalocasas** [comment]
Thanks @bbamsch !

**Comment by andisatya** [comment]
http://andisatya.atlassian.net/www.youtube.com

**Comment by andisatya** [comment]
andisatya.slack.com
