### ISSUE TITLE
TLS 1.2 support

### ISSUE THREAD

**Issue by rashthedude** [jkbrzt/httpie#536]
I'm passing the option: "--ssl=tls1.2" but this is the error I'm getting back "http: error: argument --ssl: invalid choice: u'tls1.2' (choose from 'ssl2.3', 'ssl3', 'tls1')" 

Looks as though it's not supported. The version I'm using is 0.9.6. Can anyone give me the heads up here?

Regards, 
Rashid

**Comment by jkbrzt** [comment]
> The actually available set of protocols may vary depending on your OpenSSL installation.
> — https://httpie.org/docs#ssl-version

A quick way to find out what the available protocols are, is to run `http --help`. The `--ssl` option will list all the options actually supported by your system.  For example, on my macOS/Homebrew installation it looks like this:

```bash
$ http --help | grep ' --ssl'
  --ssl {ssl2.3,ssl3,tls1,tls1.1,tls1.2}
```

**Comment by sigmavirus24** [comment]
@rashthedude is this on Ubuntu 10.04? If so, the problem is your version of Python is so incredibly old that it's ssl module does not support tls1.2. You should really not be using lucid if you care about security.

You might be able to install PyOpenSSL, pyasn1, and python-ndghttpsclient from pip to get better support but if those are not installable, you should really abandon the notion of using 10.04.

**Comment by rashthedude** [comment]
@jkbrzt and @sigmavirus24 thanks a lot for the swift response. I think the only thing that makes sense at this point is upgrading and abandoning Lucid.
